#define SECRET_WIFI_NAME "Redmi K60E NDP"
#define SECRET_WIFI_PASSWORD "11111111"

#define MQTT_BROKER_SERVER_IP "mqtt3.thingspeak.com"

#define SECRET_MQTT_USERNAME "KhQ0DTMdOzsABCM6PS8YKy4"
#define SECRET_MQTT_PASSWORD "+kSZLF63wRNNX88EbLk0WXNA"
#define SECRET_MQTT_CLIENT_ID "KhQ0DTMdOzsABCM6PS8YKy4"
#define CHANNEL_ID "2308197"
